version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - ai

  db:
    build:
      context: ./db
    ports:
      - "8080:8080"

  ai:
    build:
      context: ./ai
    ports:
      - "8000:8000"
